development:
  dialect: postgres
  url: {{envOr "DEV_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/example_development?sslmode=disable"}}
  pool: 5

test:
  dialect: postgres
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/example_test?sslmode=disable"}}

production:
  dialect: postgres
  url: {{env "DATABASE_URL"}}
