FROM andrewstucki/buffalo:0.0.1

ADD package.json yarn.lock ./

RUN yarn install --no-progress

ADD go.mod go.sum ./

RUN go mod download

ENTRYPOINT /bin/wait-for postgres-dev:5432 -- /bin/sh -c "buffalo pop migrate && buffalo dev"
